version: '3.5'

services:
  db:
    image: postgres:11.1-alpine
    networks:
      - medconnect
    environment:
      - POSTGRES_DB=medconnect
      - POSTGRES_USER=medconnect
      - POSTGRES_PASSWORD=1337
    ports:
      - 5432:5432
    restart: always
  backend:
    build: ./backend
    networks:
      - medconnect
    depends_on:
      - "db"
    ports:
      - 9100:9100
      - 8443:8443
  web:
    build: ./web
    ports:
      - 8080:80
      - 443:443
networks:
  medconnect:
    driver: bridge
