package at.connectTUdoc.backend.service;

import at.connectTUdoc.backend.exception.UserNotAuthenticatedException;
import com.google.firebase.FirebaseException;
import com.google.firebase.auth.UserRecord;

/**
 * Service to handle communication with firebase
 */
public interface FirebaseService {

  /**
   * Retrieve user id from firebase id token
   *
   * @param idToken the id token generated by firebase
   * @return the user's id
   * @throws UserNotAuthenticatedException if user is not authenticated
   */
  String getUserIdFromIdToken(String idToken) throws UserNotAuthenticatedException;

  /**
   * Retrieve user data with user id
   *
   * @param uid user id of the patient
   * @return the user record
   */
  UserRecord getUserByUid(String uid) throws FirebaseException;

  /**
   * Sends a notification to the user over FCM
   *
   * @param notificationTitle - the title of the notification
   * @param notificationBody - the body of the notification
   * @param topic - the topic to which the notification is sent
   * @return response to the sent message
   * @throws FirebaseException - if any error occurs
   */
  String sendNotification(String notificationTitle, String notificationBody, String data, String topic) throws  FirebaseException;

  /**
   * Sends a notification to the user over FCM
   *
   * @param registrationToken - token generated by the frontend
   * @param topic - the topic to subscribe to
   * @throws FirebaseException - if any error occur
   */
  void subscribeToTopic(String registrationToken, String topic) throws  FirebaseException;

}
